### ISSUE TITLE
Getting an Error While Executing Index.py

### ISSUE THREAD

**Issue by vannytheviper** [quickindex/quickindex-python#2]
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\html\parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)

**Comment by TimurTurdyev** [comment]
https://github.com/quickseo-io/quickindex-python/pull/1
there is a fix in this pull request

**Comment by dvolkhonskiy** [comment]
Thank you @TimurTurdyev and @vannytheviper! This is now merged!
